### ISSUE TITLE
Can't build it any more

### ISSUE THREAD

**Issue by sammy007** [ethereum/libethereum#130]
<pre>
[ 15%] Building CXX object libethcore/CMakeFiles/ethcore.dir/SealEngine.cpp.o
In file included from /home/farm/src/libethereum/libethcore/SealEngine.h:30:0,
                 from /home/farm/src/libethereum/libethcore/SealEngine.cpp:22:
/home/farm/src/libethereum/libethcore/BlockHeader.h: In member function ‘T dev::eth::BlockHeader::seal(unsigned int) const’:
/home/farm/src/libethereum/libethcore/BlockHeader.h:167:121: error: ‘class dev::RLP’ has no member named ‘convert’
  template <class T> T seal(unsigned _offset = 0) const { T ret; if (_offset < m_seal.size()) ret = RLP(m_seal[_offset]).convert<T>(RLP::VeryStrict); return ret; }
                                                                                                                         ^
/home/farm/src/libethereum/libethcore/BlockHeader.h:167:130: error: expected primary-expression before ‘>’ token
  template <class T> T seal(unsigned _offset = 0) const { T ret; if (_offset < m_seal.size()) ret = RLP(m_seal[_offset]).convert<T>(RLP::VeryStrict); return ret; }
                                                                                                                                  ^
make[2]: *** [libethcore/CMakeFiles/ethcore.dir/SealEngine.cpp.o] Error 1
make[1]: *** [libethcore/CMakeFiles/ethcore.dir/all] Error 2
make: *** [all] Error 2
</pre>

**Comment by bobsummerwill** [comment]
What host platform, @sammy007?
What is your command-line?

**Comment by sammy007** [comment]
ubuntu 14.04 lts, same command line, cd build && make.

**Comment by bobsummerwill** [comment]
At HEAD of everything?

Is it still broken for you as of today, rather than it being some unlucky timing while something was temporarily broken?

**Comment by bobsummerwill** [comment]
Is this with a git clone of webthree-umbrella?   Are you building the umbrella, or just libethereum?
I've just made a clean ubuntu in Azure, and will see if I can replicate the issue.

**Comment by sammy007** [comment]
With git clone libethereum

**Comment by bobsummerwill** [comment]
And how/when did you generate your makefile?   Was that with a CMake ... at the webthree-umbrella level?

I'm just looking at https://github.com/ethereum/webthree-umbrella/wiki/Linux--Generic-Building and wondering which route you took, @sammy007?

**Comment by bobsummerwill** [comment]
NOTE:   libethereum sub-module in webthree-umbrella has not been updated for 17 days, but there have been a lot of changes to the repo in that time.    If you are building repos individually, perhaps you have not updated the other repos in-sync?   Like webthree and libweb3core?

Still building ...

**Comment by sammy007** [comment]
You are right, I forgot to update other repos. Now I got this:

<pre>CMakeFiles/ethkey.dir/main.cpp.o:main.cpp:function dev::eth::TransactionSkeleton::TransactionSkeleton(): error: undefined reference to 'dev::Invalid256'</pre>

**Comment by bobsummerwill** [comment]
I just did a successful clean build against webthree-umbrella.    I'm sure it will be something to do with mixture of versions.   Did you use webthree-umbrella initially, and then manually refreshing the repos from there, or do you just have them all manually cloned in co-directories, and then cmake / make when you refresh?

**Comment by sammy007** [comment]
I have these repos manually cloned:

* libethereum
* libweb3core
* solidity
* webthree
* webthree-helpers

and trying to build just libethereum.

**Comment by bobsummerwill** [comment]
I would just follow https://github.com/ethereum/webthree-umbrella/wiki/Linux--Generic-Building if I were you, unless you have a very good reason not to?

**Comment by sammy007** [comment]
Okay.

**Comment by bobsummerwill** [comment]
The problem is that there isn't any published canonical truth about the state of the C++ builds.

The Jenkins automated builds (http://52.28.164.97/) are verifying PRs prior to submission, but there is no post-submit, so people can check in "bad stuff" without being informed that they broke something.

Also, the webthree-umbrella is manually updated, so that "known good" can get out of date fast.

Let me know if you still have issues following those instructions.   I'm not in ETHDEV but I'm strongly motivated to keep the C++ code in a good state for my own http://doublethink.co work.

**Comment by sammy007** [comment]
I want to build libethereum (just ethminer actually). I can't build libethereum separately, I can't build libethereum project using guide from umbrella <pre>webthree-helpers/scripts/ethbuild.sh --no-git --cores $(nproc) --project libethereum</pre> does not work for me. Since I am not much interested in building from source I decided to close issue, cuz it does not work just for me. I'll stick to binary release.

**Comment by bobsummerwill** [comment]
Sure ... or just build the whole umbrella, with cmake then make.   That certainly works.
Happy mining!
