### ISSUE TITLE
Runtime error in KeyManager::create() - locale name not valid

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/libethereum#138]
To get our Sailfish OS cross-build running I need to do this before running the application:

    export LC_ALL=C

To avoid a handled exception being fired from inside the JSON RPC asString(), presumably because of some locale-specific operation:

https://github.com/ethereum/libethereum/blob/develop/libethcore/KeyManager.cpp#L51

This seems to be similar to this.   And another person said they had hit this issue on a Raspberry Pi in another library.

http://stackoverflow.com/questions/19100708/mongodb-mongorestore-failure-localefacet-s-create-c-locale-name-not-valid

This *might* indicate something on the device which needs configuring more completely WRT to locales, or extra environment variables needing setting in the .bashrc, but really I think it speaking to incorrect locale handling somewhere in our code.   We should NOT be dependent on locale-specific functions if they don't need to be locale-specific.

For now I don't have a solution, only a workaround, but I suspect this issue will pop up repeatedly on the more "edge" platforms.

See https://github.com/doublethinkco/webthree-umbrella-cross/issues/21 for the full history.

**Comment by bobsummerwill** [comment]
@gavofyork said ...  yes - it's down to a missing package in ubuntu

    sudo apt-get -y install language-pack-en-base

**Comment by bobsummerwill** [comment]
Right, but I'm getting the issue on Sailfish OS, and somebody else was seemingly a suspiciously similar issue on Raspberry Pi.

Unless there is real NEED for the failing code to be machine-locale-specific, I'm thinking we would be better off hardcoding the locale within the code, if at all possible, to make the code more portable.

**Comment by bobsummerwill** [comment]
Otherwise, we're going to be stuck with distro-specific "fixes" for this for eternity :-)

**Comment by bobsummerwill** [comment]
Or are all of these locale choices deeply internal to libjson-rpc-cpp or jasoncpp?

**Comment by bobsummerwill** [comment]
See also http://stackoverflow.com/questions/1745045/stdlocale-breakage-on-macos-10-6-with-lang-en-us-utf-8 which seems to indicate that boost version might be relevant.

**Comment by bobsummerwill** [comment]
Hmm ... as per http://stackoverflow.com/questions/571359/how-do-i-set-the-proper-initial-locale-for-a-c-program-on-windows ... maybe this at the start of the app will be sufficient?

    std::locale::global(std::locale("C"));

I'll see if I can make such a fix and submit a PR.   Thanks!

**Comment by chriseth** [comment]
We had some bugs that triggered runtime assertions if the locale package was not installed. Would they be fixed by such a change?

**Comment by bobsummerwill** [comment]
I believe that might well be the case, yes.

I was probably hitting exactly those bugs, which can obviously be "fixed" on Ubuntu by installing those extra language packs, but my suspicion is that we shouldn't even be making ourselves subject to those issues in the first place, and should just be explicitly using "C" locale throughout.
