### ISSUE TITLE
ArchLinux Compile failure - crypto++ 5.6.2-4 ABI

### ISSUE THREAD

**Issue by LefterisJP** [ethereum/libethereum#141]
EDIT (Note):  This is actually a libweb3core issue, but since it's already referenced by a commit I don't want to move the issue.

Archlinux is currently having a lot of problems. I have been trying to get the C++ suite to compile again.

One of the problems is that that the crypto++ library's ABI has been rebuilt in [this package update](https://projects.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/crypto%2b%2b&id=5e8e1ea386210f898fdc3580408c2f7e43b6e8cf).

This created a binary that has incompatible ABI due to the recent GCC [change](https://gcc.gnu.org/gcc-5/changes.html#libstdcxx) introducing a new C++ abi.

The errors I get are:
```
[ 69%] Linking CXX executable bench
../libdevcrypto/libdevcrypto.so: error: undefined reference to 'CryptoPP::DL_GroupParameters_EC<CryptoPP::ECP>::StaticAlgorithmNamePrefix[abi:cxx11]()'
clang-3.7: error: linker command failed with exit code 1 (use -v to see invocation)
bench/CMakeFiles/bench.dir/build.make:114: recipe for target 'bench/bench' failed
make[2]: *** [bench/bench] Error 1
CMakeFiles/Makefile2:349: recipe for target 'bench/CMakeFiles/bench.dir/all' failed
make[1]: *** [bench/CMakeFiles/bench.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 70%] Linking CXX executable rlp
../libdevcrypto/libdevcrypto.so: error: undefined reference to 'CryptoPP::DL_GroupParameters_EC<CryptoPP::ECP>::StaticAlgorithmNamePrefix[abi:cxx11]()'
clang-3.7: error: linker command failed with exit code 1 (use -v to see invocation)
rlp/CMakeFiles/rlp.dir/build.make:114: recipe for target 'rlp/rlp' failed
make[2]: *** [rlp/rlp] Error 1
CMakeFiles/Makefile2:292: recipe for target 'rlp/CMakeFiles/rlp.dir/all' failed
make[1]: *** [rlp/CMakeFiles/rlp.dir/all] Error 2

```

What can shed some light to the problem is that according to [gcc's dual ABI docs](https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html#troubleshooting) 

>If you get linker errors about undefined references to symbols that involve types in the std::__cxx11 namespace or the tag [abi:cxx11] then it probably indicates that you are trying to link together object files that were compiled with different values for the _GLIBCXX_USE_CXX11_ABI macro. This commonly happens when linking to a third-party library that was compiled with an older version of GCC. If the third-party library cannot be rebuilt with the new ABI then you will need to recompile your code with the old ABI. 

I did try to input
```cmake
add_definitions(-D_GLIBCXX_USE_CXX11_ABI=0)
```
inside libdevcrypto's cmakefile as some of the links would suggest but this does not seem to solve the problem but instead introduce a lot more undefined references due to the ABI.

I have found a workaround that will work only if we compile with gcc. Compiling with clang does not yet offer this new ABI method and as such I don't know of a way to fix this for clang yet.

**Comment by LefterisJP** [comment]
Note: This is actually a libweb3core issue, but since it's already referenced by a commit I don't want to move the issue.

**Comment by bobsummerwill** [comment]
Yuck.
I'm having to learn about GCC ABI changes as part of cross-building.
It isn't fun.

**Comment by bobsummerwill** [comment]
Ditto.    If there is still work here, please create a new issue against webthree-umbrella.  Thanks!
