### ISSUE TITLE
ArchLinux Compile failure - jsonrpc undefined references

### ISSUE THREAD

**Issue by LefterisJP** [ethereum/libethereum#142]
When building in a fully updated archlinux I am getting these errors:

```
Scanning dependencies of target ethvm
[ 68%] Building CXX object ethvm/CMakeFiles/ethvm.dir/main.cpp.o
[ 70%] Building CXX object libethashseal/CMakeFiles/ethashseal.dir/EthashCPUMiner.cpp.o
[ 70%] Building CXX object libethashseal/CMakeFiles/ethashseal.dir/Ethash.cpp.o
[ 71%] Building CXX object libethashseal/CMakeFiles/ethashseal.dir/EthashAux.cpp.o
[ 70%] Building CXX object libethashseal/CMakeFiles/ethashseal.dir/GenesisInfo.cpp.o
[ 71%] Building CXX object libethashseal/CMakeFiles/ethashseal.dir/EthashGPUMiner.cpp.o
[ 72%] Building CXX object libethashseal/CMakeFiles/ethashseal.dir/EthashClient.cpp.o
[ 73%] Building CXX object libethashseal/CMakeFiles/ethashseal.dir/EthashProofOfWork.cpp.o
[ 74%] Linking CXX executable ethvm
../libethereum/libethereum.so: error: undefined reference to 'jsonrpc::Client::CallMethod(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Json::Value const&)'
../libethereum/libethereum.so: error: undefined reference to 'jsonrpc::JsonRpcException::JsonRpcException(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../libethereum/libethereum.so: error: undefined reference to 'jsonrpc::HttpClient::HttpClient(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
ethvm/CMakeFiles/ethvm.dir/build.make:144: recipe for target 'ethvm/ethvm' failed
make[2]: *** [ethvm/ethvm] Error 1
CMakeFiles/Makefile2:1095: recipe for target 'ethvm/CMakeFiles/ethvm.dir/all' failed
make[1]: *** [ethvm/CMakeFiles/ethvm.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 74%] Linking CXX shared library libethashseal.so
[ 74%] Built target ethashseal
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

I suspect the issue is similar to [this](https://github.com/ethereum/libethereum/issues/141) one.
Package jsoncpp was ["updated"](https://projects.archlinux.org/svntogit/packages.git/log/trunk?h=packages/jsoncpp) for the new abi and json-rpc-cpp is compiled to use it with the old one I assume.

Will have to figure out a workaround for this.

**Comment by LefterisJP** [comment]
One way to solve this is, if you had [libjsonrpc-cpp](https://aur.archlinux.org/packages/libjson-rpc-cpp/) package to remove it and download and build [libjson-rpc-cpp-git/](https://aur.archlinux.org/packages/libjson-rpc-cpp-git/) from the AUR. It seems to have a fix in for the ABI problem

**Comment by janx** [comment]
Same problem on archlinux.

I tried libjson-rpc-cpp-git, doesn't work. The libjson-rpc-cpp version is 0.6.0, is that correct?

**Comment by janx** [comment]
I got it compiled after comment out `patch -Np1 -i ../gcc5.patch` in PKGBUILD of libjson-rpc-cpp.

**Comment by LefterisJP** [comment]
Hm then this is a gcc ABI issue again.

**Comment by bobsummerwill** [comment]
Hey @LefterisJP!
Any thoughts on how to deal with these ABI issues on Arch?   Is there some resolution possible?

**Comment by LefterisJP** [comment]
Yes, use up to date packages as I said in my comment from December.

**Comment by bobsummerwill** [comment]
So is there any more work to be done here?
Any updates required to the instructions in https://github.com/ethereum/webthree-umbrella/wiki/Building-on-ArchLinux?

I have never used Arch, and am in no position to make reliable updates to that doc, or to assess its completeness or correctness.

**Comment by bobsummerwill** [comment]
OK - Looks like there is nothing more to do here.    Please open a new issue against webthree-umbrella if  we still have work!
