### ISSUE TITLE
Sync over eth/pv62 and eth/pv63

### ISSUE THREAD

**Issue by arkpar** [ethereum/libethereum#52]
PV63 fastsync mode, launched if PV63 peers available && (start || a new block is noted with height > N + currentHeight)

1. Get last N block headers by hashes in ascending tree order. Pick block X = Latest - N 
2. In parallel:
 * Download state tree nodes for block X from PV63 peers
 * Download transaction receipts for blocks 1 to X from PV63 peers
 * Download 1..X block bodies and headers from PV62 and PV63 peers
3. Once done
 * Insert blocks
 * Insert state

PV62 sync mode, launched if no PV62 peers available && (start || a new block is noted with height > N + currentHeight)
2. Split chain into chunks of size M
Download chunks in parallel. For each chunk:
 * Download block headers in ascending tree order until a known block hash is met
 * Download block bodies
3. Reorder blocks and insert them into block queue

Keep up mode, launched when a new block is noted with height < N + currentHeight
* Download headers from a single peer in ascending tree order until a known block hash is met
* Download bodies

General:

* Validate all attack vectors, review code audit report.

**Comment by bobsummerwill** [comment]
@chriseth Is PV63 still going to be happening?   Or just PV62?
I was under the impression that PV63 was for the originally planned Light Client support, and was superceded by the LES1 sub-protocol?

**Comment by chriseth** [comment]
Your impression is right. PV63 is used for "fast sync", but light clients will likely use a different protocol. At the current capacity, neither PV63 nor LES1 are planned, although both are really important as the C++ implementation is a likely candidate for running on embedded hardware.
External contributions are welcome, and I'm more than happy to give a hand.

**Comment by chriseth** [comment]
Moving to webthree-umbrella.
